<?php

namespace el_api_v1;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-12 at 11:36:33.
 */
class passwordHashTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var passwordHash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new passwordHash;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers el_api_v1\passwordHash::unique_salt
     * @todo   Implement testUnique_salt().
     */
    public function testUnique_salt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers el_api_v1\passwordHash::hash
     * @todo   Implement testHash().
     */
    public function testHash() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers el_api_v1\passwordHash::check_password
     * @todo   Implement testCheck_password().
     */
    public function testCheck_password() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
